# Data Cleaning and Insertion into MSSQL

Importer Biblioteker og Opret Forbindelse til MSSQL

In [24]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float
from sqlalchemy import inspect

# Load the CSV data into a DataFrame
file_path = '2016_-_Cities_Emissions_Reduction_Targets_20240207.csv'
df = pd.read_csv(file_path)

# Display the initial data structure
print("Initial Data:")
print(df.head())
print(df.info())

# Handling Missing Values
df['Baseline emissions (metric tonnes CO2e)'] = df['Baseline emissions (metric tonnes CO2e)'].fillna(df['Baseline emissions (metric tonnes CO2e)'].median())
df['Percentage reduction target'] = df['Percentage reduction target'].fillna(df['Percentage reduction target'].median())

df['City Short Name'] = df['City Short Name'].fillna('Unknown City')
df['Country'] = df['Country'].fillna('Unknown Country')
df['Organisation'] = df['Organisation'].fillna('Unknown Organisation')

df['Reporting Year'] = pd.to_datetime(df['Reporting Year'], format='%Y', errors='coerce').dt.year
df['Target date'] = pd.to_datetime(df['Target date'], format='%Y', errors='coerce').dt.year

df['Reporting Year'] = df['Reporting Year'].fillna(0)
df['Target date'] = df['Target date'].fillna(0)

df['City Short Name'] = df['City Short Name'].str.title()
df.drop_duplicates(inplace=True)
df['Organisation'] = df['Organisation'].str.strip()
df['Country'] = df['Country'].replace({'Usa': 'USA', 'Uk': 'United Kingdom'})
df = df[df['Percentage reduction target'] >= 0]

# Step 10: Exporting Clean Data
cleaned_file_path = 'cleaned_data_MSSQL_2016_-_Cities_Emissions_Reduction_Targets_20240207.csv'
df.to_csv(cleaned_file_path, index=False)

# Define the connection parameters
server = 'JEFFREY'
database = 'EksamensProjekt_DB'
username = 'Oechsner'
password = '1234'
connection_string = f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'
engine = create_engine(connection_string)

# Define the metadata and table schema
metadata = MetaData()

# Define the table schema without setting Account No as the primary key
table = Table(
    'Cities_Emissions_Reduction_Targets_2016', metadata,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('Account No', Integer),
    Column('Organisation', String),
    Column('Country', String),
    Column('City Short Name', String),
    Column('C40', String),
    Column('Reporting Year', Integer),
    Column('Sector', String),
    Column('Target boundary', String),
    Column('Baseline year', String),
    Column('Baseline emissions (metric tonnes CO2e)', Float),
    Column('Percentage reduction target', Float),
    Column('Target date', Integer),
    Column('Comment', String),
    Column('City Location', String),
    Column('Country Location', String)
)

# Drop the table if it already exists to ensure we start fresh
inspector = inspect(engine)
if 'Cities_Emissions_Reduction_Targets_2016' in inspector.get_table_names():
    table.drop(engine)

# Create the table in the database
metadata.create_all(engine)

# Insert data into the table without 'id' column
df.to_sql('Cities_Emissions_Reduction_Targets_2016', engine, if_exists='append', index=False)

print("Data successfully inserted into the Cities_Emissions_Reduction_Targets_2016 table.")

Initial Data:
             Organisation  Account No  Country      City Short Name  C40  \
0           Odder Kommune       58796  Denmark        Odder Kommune  NaN
1        Comune di Napoli       36158    Italy               Napoli  NaN
2     Egedal Municipality       62855  Denmark  Egedal Municipality  NaN
3            Yilan County       61753   Taiwan               Yilan   NaN
4  City of Emeryville, CA       61790      USA       Emeryville, CA  NaN

   Reporting Year Sector              Target boundary Baseline year  \
0            2016  Total                          NaN          2010
1            2016  Total                          NaN          2005
2            2016  Total                          NaN          2009
3            2016  Total                          NaN          2009
4            2016  Total  Overall community emissions          2004

   Baseline emissions (metric tonnes CO2e)  Percentage reduction target  \
0                                   6136.0                          2.0
1                                2913434.0                         25.0
2                                 268000.0                          7.0
3                                3804493.0                         35.0
4                                 178832.0                         40.0

   Target date                                            Comment  \
0          NaN                                                NaN
1       2020.0                                                NaN
2       2020.0  The municipality are increasing in terms of ci...
3       2020.0                                                NaN
4       2030.0                                                NaN

              City Location        Country Location
0    (55.975718, 10.149958)    (56.26392, 9.501785)
1  (40.8419943, 14.2513831)    (41.87194, 12.56738)
2    (55.795045, 12.238733)    (56.26392, 9.501785)
3    (24.702107, 121.73775)  (23.69781, 120.960515)
4  (37.831316, -122.285247)  (37.09024, -95.712891)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 15 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Organisation                             280 non-null    object
 1   Account No                               280 non-null    int64
 2   Country                                  280 non-null    object
 3   City Short Name                          280 non-null    object
 4   C40                                      83 non-null     object
 5   Reporting Year                           280 non-null    int64
 6   Sector                                   268 non-null    object
 7   Target boundary                          222 non-null    object
 8   Baseline year                            275 non-null    object
 9   Baseline emissions (metric tonnes CO2e)  262 non-null    float64
 10  Percentage reduction target              280 non-null    float64
 11  Target date                              270 non-null    float64
 12  Comment                                  138 non-null    object
 13  City Location                            280 non-null    object
 14  Country Location                         280 non-null    object
dtypes: float64(3), int64(2), object(10)
memory usage: 32.9+ KB
None
Data successfully inserted into the Cities_Emissions_Reduction_Targets_2016 table.

# 2016_-_Citywide_GHG_Emissions_20240207.csv

In [5]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float
from sqlalchemy import inspect

# Load the CSV data into a DataFrame
file_path = '2016_-_Citywide_GHG_Emissions_20240207.csv'
df = pd.read_csv(file_path)

# Clean column names
df.columns = [col.strip().replace('\u200b', '') for col in df.columns]

# Display the initial data structure
print("Initial Data:")
print(df.head())
print(df.info())

# Handling Missing Values
df['Total City-wide Emissions (metric tonnes CO2e)'] = df['Total City-wide Emissions (metric tonnes CO2e)'].fillna(df['Total City-wide Emissions (metric tonnes CO2e)'].median())
df['Total Scope 1 Emissions (metric tonnes CO2e)'] = df['Total Scope 1 Emissions (metric tonnes CO2e)'].fillna(df['Total Scope 1 Emissions (metric tonnes CO2e)'].median())
df['Total Scope 2 Emissions (metric tonnes CO2e)'] = df['Total Scope 2 Emissions (metric tonnes CO2e)'].fillna(df['Total Scope 2 Emissions (metric tonnes CO2e)'].median())

df['City Name'] = df['City Name'].fillna('Unknown City')
df['Country'] = df['Country'].fillna('Unknown Country')
df['Primary Methodology'] = df['Primary Methodology'].fillna('Unknown Methodology')

df['Reporting Year'] = pd.to_datetime(df['Reporting Year'], format='%Y', errors='coerce').dt.year
df['Reporting Year'] = df['Reporting Year'].fillna(0)

df['City Name'] = df['City Name'].str.title()
df.drop_duplicates(inplace=True)
df['City Name'] = df['City Name'].str.strip()
df['Country'] = df['Country'].replace({'Usa': 'USA', 'Uk': 'United Kingdom'})

# Step 10: Exporting Clean Data
cleaned_file_path = 'cleaned_data_MSSQL_2016_-_Citywide_GHG_Emissions_20240207.csv'
df.to_csv(cleaned_file_path, index=False)

# Define the connection parameters
server = 'JEFFREY'
database = 'EksamensProjekt_DB'
username = 'Oechsner'
password = '1234'
connection_string = f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'
engine = create_engine(connection_string)

# Define the metadata and table schema
metadata = MetaData()

# Define the table schema with an auto-incrementing primary key
table = Table(
    'Citywide_GHG_Emissions_2016', metadata,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('Account Number', Integer),
    Column('City Name', String),
    Column('Country', String),
    Column('City Short Name', String),
    Column('C40', String),
    Column('Reporting Year', Integer),
    Column('Measurement Year', String),  # Changed to String to match the data format in the CSV
    Column('Boundary', String),
    Column('Primary Methodology', String),
    Column('Methodology Details', String),
    Column('Gases included', String),
    Column('Total City-wide Emissions (metric tonnes CO2e)', Float),
    Column('Total Scope 1 Emissions (metric tonnes CO2e)', Float),
    Column('Total Scope 2 Emissions (metric tonnes CO2e)', Float),
    Column('Increase/Decrease from last year', String),
    Column('Reason for increase/decrease in emissions', String),
    Column('Current Population Year', Integer),
    Column('Current Population', Float),
    Column('City GDP', Float),
    Column('GDP Currency', String),
    Column('Year of GDP', Float),
    Column('GDP Source', String),
    Column('Average annual temperature (in Celsius)', Float),
    Column('Land area (in square km)', Float),
    Column('Average altitude (m)', Float),
    Column('City Location', String),
    Column('Country Location', String)
)

# Drop the table if it already exists to ensure we start fresh
inspector = inspect(engine)
if 'Citywide_GHG_Emissions_2016' in inspector.get_table_names():
    table.drop(engine)

# Create the table in the database
metadata.create_all(engine)

# Insert data into the table without 'id' column
df.to_sql('Citywide_GHG_Emissions_2016', engine, if_exists='append', index=False)

print("Data successfully inserted into the Citywide_GHG_Emissions_2016 table.")

Initial Data:
   Account Number            City Name         Country City Short Name  C40  \
0           35894    Ville de Montreal          Canada        Montreal  NaN
1           35898   Greater Manchester  United Kingdom      Manchester  NaN
2           54128         City of Reno             USA            Reno  NaN
3           35879  City of Minneapolis             USA     Minneapolis  NaN
4           50558   City of London, ON          Canada      London, ON  NaN

   Reporting Year        Measurement Year  \
0            2016  12/31/2009 12:00:00 AM
1            2016  12/31/2013 12:00:00 AM
2            2016  12/31/2014 12:00:00 AM
3            2016  12/31/2014 12:00:00 AM
4            2016  12/31/2014 12:00:00 AM

                                            Boundary  \
0  Other: The regional entity that constitutes th...
1                                A metropolitan area
2      Administrative boundary of a local government
3      Administrative boundary of a local government
4      Administrative boundary of a local government

                                 Primary Methodology  \
0  2006 IPCC Guidelines for National Greenhouse G...
1  Global Protocol for Community-Scale Greenhouse...
2  Global Protocol for Community-Scale Greenhouse...
3  U.S. Community Protocol for Accounting and Rep...
4  International Emissions Analysis Protocol (ICLEI)

                                 Methodology Details  ... Current Population  \
0  2006 IPCC Guidelines for National Greenhouse G...  ...          1886481.0
1  A GPC Compliant dataset has been established f...  ...          2762000.0
2  Also utilized the U.S. Community Protocol for ...  ...           236995.0
3  A note regarding how double counting is avoide...  ...           407207.0
4  as adapted by ICLEI Canada for use in the FCM'...  ...           375000.0

       City GDP             GDP Currency  Year of GDP  \
0  1.201180e+11  CAD     Canadian Dollar       2014.0
1  8.777300e+10                      NaN       2013.0
2  1.000000e+10        USD     US Dollar       2014.0
3  2.357000e+11        USD     US Dollar       2014.0
4  1.540000e+10  CAD     Canadian Dollar       2014.0

                                          GDP Source  \
0  Ville de Montréal, Montréal en statistiques, h...
1  UK ONS (using 1.56 USD/GBP) Figures provided i...
2                    Bureau of Economic Analysis10.4
3  http://www.bea.gov/iTable/iTable.cfm?reqid=70&...
4  Conference Board of Canada, London Census Metr...

  Average annual temperature (in Celsius)  Land area (in square km)  \
0                                     6.8                     500.0
1                                     9.5                    1277.0
2                                    10.4                     288.0
3                                     7.9                     139.8
4                                     7.9                     421.0

   Average altitude (m)              City Location          Country Location
0                  17.0  (45.5086699, -73.5539925)  (56.130366, -106.346771)
1                 250.0   (53.4575955, -2.1578377)    (55.378051, -3.435973)
2                1373.0       (39.5296, -119.8138)    (37.09024, -95.712891)
3                 264.0     (44.983334, -93.26667)    (37.09024, -95.712891)
4                 251.0        (42.9837, -81.2497)  (56.130366, -106.346771)

[5 rows x 27 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 27 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Account Number                                  187 non-null    int64
 1   City Name                                       187 non-null    object
 2   Country                                         187 non-null    object
 3   City Short Name                                 187 non-null    object
 4   C40                                             54 non-null     object
 5   Reporting Year                                  187 non-null    int64
 6   Measurement Year                                187 non-null    object
 7   Boundary                                        187 non-null    object
 8   Primary Methodology                             187 non-null    object
 9   Methodology Details                             133 non-null    object
 10  Gases included                                  181 non-null    object
 11  Total City-wide Emissions (metric tonnes CO2e)  187 non-null    float64
 12  Total Scope 1 Emissions (metric tonnes CO2e)    134 non-null    float64
 13  Total Scope 2 Emissions (metric tonnes CO2e)    132 non-null    float64
 14  Increase/Decrease from last year                166 non-null    object
 15  Reason for increase/decrease in emissions       144 non-null    object
 16  Current Population Year                         187 non-null    int64
 17  Current Population                              185 non-null    float64
 18  City GDP                                        130 non-null    float64
 19  GDP Currency                                    123 non-null    object
 20  Year of GDP                                     137 non-null    float64
 21  GDP Source                                      130 non-null    object
 22  Average annual temperature (in Celsius)         177 non-null    float64
 23  Land area (in square km)                        184 non-null    float64
 24  Average altitude (m)                            168 non-null    float64
 25  City Location                                   187 non-null    object
 26  Country Location                                187 non-null    object
dtypes: float64(9), int64(3), object(15)
memory usage: 39.6+ KB
None
Data successfully inserted into the Citywide_GHG_Emissions_2016 table.

Primary Key: Added an auto-incrementing primary key column (id).
Data Cleaning: Filled missing values in key columns with median values or default strings.
Export Clean Data: Saved the cleaned DataFrame to a new CSV file.
Database Table Creation: Created a new table in SQL Server with the appropriate schema and inserted the cleaned data.

Explanation:
  Load CSV: Read the CSV file into a DataFrame using pd.read_csv   Display Initial Data: Print the first few rows and the structure of the DataFrame to understand its conten    Display Column Names: Print the column names to ensure correct column names are used in the subsequent ste
    Handle Missing Val      Fill numeric columns with median values to avoid skewing the        Fill categorical columns with a placeholder value to maintain consisy.
    Data Type Conversions: Convert date columns to a datetime format for consistency and easier manipuon.
    Standardize Formats: Standardize text formats (e.g., capitalizing city names) to maintain consncy.
    Remove Duplicates: Remove any duplicate rows to ensure each record iique.
    Trim and Clean Strings: Remove extra spaces from strialues.
    Consolidate Categories: Replace similar categories (e.g., 'Usa' to 'USA') for cstency.
    Validate Data: Ensure all emissions values are negative.
    Create Unique Identifiers: Create a unique identifier for each row based on the 'Account nu' column.
    Export Clean Data: Save the cleaned DataFrame to a CSV file.
    Define Connection Parameters: Set up the connection parame for MSSQL.
    Create and Insert Data: Write the cleaned data to a new table in the MSSQL database.

# 2017_-_Cities_Community_Wide_Emissions.csv

In [83]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float
from sqlalchemy import inspect

# Step 1: Load the CSV data into a DataFrame
file_path = '2017_-_Cities_Community_Wide_Emissions.csv'
df = pd.read_csv(file_path)

# Display the initial data structure
print("Initial Data:")
print(df.head())
print(df.info())

# Step 2: Clean column names: remove leading/trailing spaces, hidden characters, and replace spaces with underscores
df.columns = df.columns.str.strip().str.replace('\u200b', '').str.replace(' ', '_')

# Step 3: Handle missing values
# Fill numeric columns with median values
numeric_columns = [
    'Total_emissions_(metric_tonnes_CO2e)', 
    'Total_Scope_1_Emissions_(metric_tonnes_CO2e)',
    'Total_Scope_2_Emissions_(metric_tonnes_CO2e)',
    'Population',
    'Population_year'
]

for column in numeric_columns:
    if column in df.columns:
        df[column] = df[column].fillna(df[column].median())

# Fill categorical columns with a placeholder value
categorical_columns = ['City', 'Country', 'Region']

for column in categorical_columns:
    if column in df.columns:
        df[column] = df[column].fillna(f'Unknown_{column}')

# Handle date columns
def clean_date_column(column):
    df[column] = pd.to_datetime(df[column], errors='coerce').dt.year
    df[column] = df[column].fillna(0).astype(int)

date_columns = ['Reporting_year', 'Accounting_year']

for column in date_columns:
    if column in df.columns:
        try:
            df[column] = pd.to_datetime(df[column], errors='coerce').dt.year
            df[column] = df[column].fillna(0).astype(int)
        except Exception as e:
            print(f"Error converting column {column}: {e}")
            df[column] = 0

# Ensure that columns expected to be integers do not contain non-integer values
integer_columns = ['Account_number', 'Reporting_year', 'Accounting_year']

for column in integer_columns:
    if column in df.columns:
        df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0).astype(int)

# Step 4: Standardize formats and handle duplicates
if 'City' in df.columns:
    df['City'] = df['City'].str.title()

df.drop_duplicates(inplace=True)

if 'Country' in df.columns:
    df['Country'] = df['Country'].replace({'Usa': 'USA', 'Uk': 'United_Kingdom'})

# Step 5: Ensure column names match the SQL Server schema
df.rename(columns={
    'Total_emissions_(metric_tonnes_CO2e)': 'Total_emissions_metric_tonnes_CO2e',
    'Total_Scope_1_Emissions_(metric_tonnes_CO2e)': 'Scope_1_emissions_metric_tonnes_CO2e',
    'Total_Scope_2_Emissions_(metric_tonnes_CO2e)': 'Scope_2_emissions_metric_tonnes_CO2e'
}, inplace=True)

# Ensure the DataFrame has the expected columns
expected_columns = [
    'Account_number', 'Organization', 'City', 'Country', 'Region', 'C40', 'Access',
    'Reporting_year', 'Accounting_year', 'Boundary', 'Total_emissions_metric_tonnes_CO2e',
    'Scope_1_emissions_metric_tonnes_CO2e', 'Scope_2_emissions_metric_tonnes_CO2e',
    'Population', 'Population_year', 'Comment'
]

# Add missing columns if they don't exist
for column in expected_columns:
    if column not in df.columns:
        df[column] = None

# Reorder the columns to match the expected schema
df = df[expected_columns]

# Verify the cleaned DataFrame before inserting
print("\nCleaned DataFrame:")
print(df.head())
print(df.info())

print("\nMissing Values After Cleaning:")
print(df.isna().sum())

# Exporting Clean Data
cleaned_file_path = 'cleaned_data_MSSQL_Cities_Community_Wide_Emissions_2017.csv'
df.to_csv(cleaned_file_path, index=False)

# Step 6: Insert the cleaned DataFrame into MSSQL

# Define the connection parameters
server = 'JEFFREY'
database = 'EksamensProjekt_DB'
username = 'Oechsner'
password = '1234'
connection_string = f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'
engine = create_engine(connection_string)

# Define the metadata and table schema
metadata = MetaData()

# Define the table schema with 'id' as primary key
table = Table(
    'Cities_Community_Wide_Emissions_2017', metadata,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('Account_number', Integer),
    Column('Organization', String),
    Column('City', String),
    Column('Country', String),
    Column('Region', String),
    Column('C40', String),
    Column('Access', String),
    Column('Reporting_year', Integer),
    Column('Accounting_year', Integer),
    Column('Boundary', String),
    Column('Total_emissions_metric_tonnes_CO2e', Float),
    Column('Scope_1_emissions_metric_tonnes_CO2e', Float),
    Column('Scope_2_emissions_metric_tonnes_CO2e', Float),
    Column('Population', Float),
    Column('Population_year', Float),
    Column('Comment', String)
)

# Drop the table if it already exists to ensure we start fresh
inspector = inspect(engine)
if 'Cities_Community_Wide_Emissions_2017' in inspector.get_table_names():
    table.drop(engine)

# Create the table in the database
metadata.create_all(engine)

# Insert data into the table
df.to_sql('Cities_Community_Wide_Emissions_2017', engine, if_exists='append', index=False)

print("Data successfully inserted into the Cities_Community_Wide_Emissions_2017 table.")

Initial Data:
   Account number                     Organization                 City  \
0           49363  Nelson Mandela Bay Municipality  Nelson Mandela Bay
1           31171           Ayuntamiento de Madrid               Madrid
2            3417                    New York City        New York City
3           59537               City of Denton, TX           Denton, TX
4           35894                Ville de Montreal             Montreal

        Country         Region  C40  Access  Reporting year  \
0  South Africa         Africa  NaN  Public            2017
1         Spain         Europe  C40  Public            2017
2           USA  North America  C40  Public            2017
3           USA  North America  NaN  Public            2017
4        Canada  North America  C40  Public            2017

           Accounting year                                       Boundary  \
0  2013-07-01 - 2014-06-30                            A metropolitan area
1  2014-01-01 - 2014-12-31  Administrative boundary of a local government
2  2015-01-01 - 2015-12-31  Administrative boundary of a local government
3  2015-01-01 - 2015-12-31  Administrative boundary of a local government
4  2013-01-01 - 2013-12-31                            A metropolitan area

   ... Population year           GDP                GDP Currency  GDP Year  \
0  ...            2011  5.214700e+04  ZAR     South African Rand    2010.0
1  ...            2016  1.293780e+11                EUR     Euro    2015.0
2  ...            2016  1.558520e+12           USD     US Dollar    2015.0
3  ...            2015           NaN                         NaN       NaN
4  ...            2013  1.154128e+08     CAD     Canadian Dollar    2013.0

                                          GDP Source  \
0           Built Environment Performance Plan(BEPP)
1  Contabilidad Municipal Trimestral. Ciudad de M...
2  http://www.brookings.edu/research/reports2/201...
3                                                NaN
4               Institut de la statistique du Québec

   Average annual temperature (in Celsius)​  ​Average altitude (m)  \
0                                      17.5                   69.0
1                                      15.0                  655.0
2                                      13.0                   10.0
3                                      18.2                  192.0
4                                       6.8                   17.0

  ​Land area (in square km)              City Location  \
0                    1950.0    (-33.745241, 25.568108)
1                     604.0   (40.1076253, -3.3875673)
2                     784.0  (40.7127837, -74.0059413)
3                     227.8    (33.214841, -97.133068)
4                     500.0  (45.5086699, -73.5539925)

           Country Location
0   (-30.559482, 22.937506)
1     (40.463667, -3.74922)
2    (37.09024, -95.712891)
3    (37.09024, -95.712891)
4  (56.130366, -106.346771)

[5 rows x 31 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 31 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Account number                                229 non-null    int64
 1   Organization                                  229 non-null    object
 2   City                                          229 non-null    object
 3   Country                                       229 non-null    object
 4   Region                                        229 non-null    object
 5   C40                                           56 non-null     object
 6   Access                                        229 non-null    object
 7   Reporting year                                229 non-null    int64
 8   Accounting year                               229 non-null    object
 9   Boundary                                      229 non-null    object
 10  Protocol                                      229 non-null    object
 11  Protocol column                               151 non-null    object
 12  Gases included                                111 non-null    object
 13  Total emissions (metric tonnes CO2e)          217 non-null    float64
 14  Scopes Included                               229 non-null    object
 15  Total Scope 1 Emissions (metric tonnes CO2e)  173 non-null    float64
 16  Total Scope 2 Emissions (metric tonnes CO2e)  172 non-null    float64
 17  Comment                                       79 non-null     object
 18  Increase/Decrease from last year              209 non-null    object
 19  Reason for increase/decrease in emissions     178 non-null    object
 20  Population                                    229 non-null    int64
 21  Population year                               229 non-null    int64
 22  GDP                                           181 non-null    float64
 23  GDP Currency                                  184 non-null    object
 24  GDP Year                                      185 non-null    float64
 25  GDP Source                                    178 non-null    object
 26  Average annual temperature (in Celsius)​      223 non-null    float64
 27  ​Average altitude (m)                         207 non-null    float64
 28  ​Land area (in square km)                     228 non-null    float64
 29  City Location                                 229 non-null    object
 30  Country Location                              229 non-null    object
dtypes: float64(8), int64(4), object(19)
memory usage: 55.6+ KB
None
Error converting column Accounting_year: Can only use .dt accessor with datetimelike values

Cleaned DataFrame:
   Account_number                     Organization                 City  \
0           49363  Nelson Mandela Bay Municipality  Nelson Mandela Bay
1           31171           Ayuntamiento de Madrid               Madrid
2            3417                    New York City        New York City
3           59537               City of Denton, TX           Denton, Tx
4           35894                Ville de Montreal             Montreal

        Country         Region  C40  Access  Reporting_year  Accounting_year  \
0  South Africa         Africa  NaN  Public            1970                0
1         Spain         Europe  C40  Public            1970                0
2           USA  North America  C40  Public            1970                0
3           USA  North America  NaN  Public            1970                0
4        Canada  North America  C40  Public            1970                0

                                        Boundary  \
0                            A metropolitan area
1  Administrative boundary of a local government
2  Administrative boundary of a local government
3  Administrative boundary of a local government
4                            A metropolitan area

   Total_emissions_metric_tonnes_CO2e  Scope_1_emissions_metric_tonnes_CO2e  \
0                          12232310.0                             2249502.0
1                           9236196.0                             7069783.0
2                          52042186.0                            38962264.0
3                           1604007.0                              898681.0
4                          10197555.0                            10729801.0

   Scope_2_emissions_metric_tonnes_CO2e  Population  Population_year  \
0                             9982808.0     1152115             2011
1                             3408424.0     3165883             2016
2                            14343743.0     8537673             2016
3                              759270.0      131044             2015
4                               61912.0     1959987             2013

                                             Comment
0                                                NaN
1                                                NaN
2                                                NaN
3  The one sector of tracking and reporting accur...
4                                                NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 16 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Account_number                        229 non-null    int32
 1   Organization                          229 non-null    object
 2   City                                  229 non-null    object
 3   Country                               229 non-null    object
 4   Region                                229 non-null    object
 5   C40                                   56 non-null     object
 6   Access                                229 non-null    object
 7   Reporting_year                        229 non-null    int32
 8   Accounting_year                       229 non-null    int32
 9   Boundary                              229 non-null    object
 10  Total_emissions_metric_tonnes_CO2e    229 non-null    float64
 11  Scope_1_emissions_metric_tonnes_CO2e  229 non-null    float64
 12  Scope_2_emissions_metric_tonnes_CO2e  229 non-null    float64
 13  Population                            229 non-null    int64
 14  Population_year                       229 non-null    int64
 15  Comment                               79 non-null     object
dtypes: float64(3), int32(3), int64(2), object(8)
memory usage: 26.1+ KB
None

Missing Values After Cleaning:
Account_number                            0
Organization                              0
City                                      0
Country                                   0
Region                                    0
C40                                     173
Access                                    0
Reporting_year                            0
Accounting_year                           0
Boundary                                  0
Total_emissions_metric_tonnes_CO2e        0
Scope_1_emissions_metric_tonnes_CO2e      0
Scope_2_emissions_metric_tonnes_CO2e      0
Population                                0
Population_year                           0
Comment                                 150
dtype: int64

C:\Users\jeffo\AppData\Local\Temp\ipykernel_3644\2962568842.py:48: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[column] = pd.to_datetime(df[column], errors='coerce').dt.year
C:\Users\jeffo\AppData\Local\Temp\ipykernel_3644\2962568842.py:48: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df[column] = pd.to_datetime(df[column], errors='coerce').dt.year

Data successfully inserted into the Cities_Community_Wide_Emissions_2017 table.

Explanation:

Load CSV: Read the CSV file into a DataFrame using pd.read_csv.
Display Initial Data: Print the first few rows and the structure of the DataFrame to understand its content.
Display Column Names: Print the column names to ensure correct column names are used in the subsequent steps.
Handle Missing Values:
Fill numeric columns with median values to avoid skewing the data.
Fill categorical columns with a placeholder value to maintain consistency.
Data Type Conversions: Convert date columns to a datetime format for consistency and easier manipulation.
Standardize Formats: Standardize text formats (e.g., capitalizing city names) to maintain consistency.
Remove Duplicates: Remove any duplicate rows to ensure each record is unique.
Trim and Clean Strings: Remove extra spaces from string values.
Consolidate Categories: Replace similar categories (e.g., 'Usa' to 'USA') for consistency.
Validate Data: Ensure all emissions values are non-negative.
Create Unique Identifiers: Create a unique identifier for each row based on the 'Account number' column.
Export Clean Data: Save the cleaned DataFrame to a new CSV file.
Define Connection Parameters: Set up the connection parameters for MSSQL.
Create and Insert Data: Write the cleaned data to a new table in the MSSQL database.

# 2017_-_Cities_Emissions_Reduction_Targets_20240207.csv

In [68]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float
from sqlalchemy import inspect

# Step 1: Load the CSV data into a DataFrame
file_path = '2017_-_Cities_Emissions_Reduction_Targets_20240207.csv'
df = pd.read_csv(file_path)

# Display the initial data structure
print("Initial Data:")
print(df.head())
print(df.info())

# Step 2: Clean column names: remove leading/trailing spaces, hidden characters, and replace spaces with underscores
df.columns = df.columns.str.strip().str.replace('\u200b', '').str.replace(' ', '_')

# Step 3: Handle missing values
# Fill numeric columns with median values
numeric_columns = [
    'Baseline_emissions_(metric_tonnes_CO2e)', 
    'Percentage_reduction_target',
    'Estimated_business_as_usual_absolute_emissions_in_target_year_(metric_tonnes_CO2e)',
    'Population',
    'Population_Year'
]

for column in numeric_columns:
    if column in df.columns:
        df[column] = df[column].fillna(df[column].median())

# Fill categorical columns with a placeholder value
categorical_columns = ['City', 'Country', 'Organisation', 'Region']

for column in categorical_columns:
    if column in df.columns:
        df[column] = df[column].fillna(f'Unknown_{column}')

# Convert date columns to integer format and fill with a default value if they remain NaN
date_columns = ['Reporting_year', 'Target_date']

for column in date_columns:
    if column in df.columns:
        df[column] = pd.to_datetime(df[column], format='%Y', errors='coerce').dt.year
        df[column] = df[column].fillna(0).astype(int)

# Ensure that columns expected to be integers do not contain non-integer values
integer_columns = ['Account_No', 'Reporting_year', 'Target_date', 'Baseline_year']

for column in integer_columns:
    if column in df.columns:
        df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0).astype(int)

# Step 4: Standardize formats and handle duplicates
if 'City' in df.columns:
    df['City'] = df['City'].str.title()

df.drop_duplicates(inplace=True)

if 'Organisation' in df.columns:
    df['Organisation'] = df['Organisation'].str.strip()

if 'Country' in df.columns:
    df['Country'] = df['Country'].replace({'Usa': 'USA', 'Uk': 'United_Kingdom'})

# Validate data
if 'Percentage_reduction_target' in df.columns:
    df = df[df['Percentage_reduction_target'] >= 0]

# Step 5: Ensure column names match the SQL Server schema
df.rename(columns={
    'Baseline_emissions_(metric_tonnes_CO2e)': 'Baseline_emissions_metric_tonnes_CO2e',
    'Estimated_business_as_usual_absolute_emissions_in_target_year_(metric_tonnes_CO2e)': 'Estimated_business_as_usual_absolute_emissions_in_target_year_metric_tonnes_CO2e',
    'Intensity_unit_(emissions_per)': 'Intensity_unit_emissions_per'
}, inplace=True)

# Ensure the DataFrame has the expected columns
expected_columns = [
    'Account_No', 'Organisation', 'City', 'Country', 'Region', 'Access', 'C40',
    'Reporting_year', 'Type_of_target', 'Sector', 'Baseline_year',
    'Baseline_emissions_metric_tonnes_CO2e', 'Percentage_reduction_target', 'Target_date',
    'Estimated_business_as_usual_absolute_emissions_in_target_year_metric_tonnes_CO2e',
    'Intensity_unit_emissions_per', 'Comment', 'Population', 'Population_Year',
    'City_Location', 'Country_Location'
]

# Add missing columns if they don't exist
for column in expected_columns:
    if column not in df.columns:
        df[column] = None

# Reorder the columns to match the expected schema
df = df[expected_columns]

# Verify the cleaned DataFrame before inserting
print("\nCleaned DataFrame:")
print(df.head())
print(df.info())

print("\nMissing Values After Cleaning:")
print(df.isna().sum())

# Exporting Clean Data
cleaned_file_path = 'cleaned_data_MSSQL_Cities_Emissions_Reduction_Targets_2017.csv'
df.to_csv(cleaned_file_path, index=False)

# Step 6: Insert the cleaned DataFrame into MSSQL

# Define the connection parameters
server = 'JEFFREY'
database = 'EksamensProjekt_DB'
username = 'Oechsner'
password = '1234'
connection_string = f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'
engine = create_engine(connection_string)

# Define the metadata and table schema
metadata = MetaData()

# Define the table schema with 'id' as primary key
table = Table(
    'Cities_Emissions_Reduction_Targets_2017', metadata,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('Account_No', Integer),
    Column('Organisation', String),
    Column('City', String),
    Column('Country', String),
    Column('Region', String),
    Column('Access', String),
    Column('C40', String),
    Column('Reporting_year', Integer),
    Column('Type_of_target', String),
    Column('Sector', String),
    Column('Baseline_year', Integer),
    Column('Baseline_emissions_metric_tonnes_CO2e', Float),
    Column('Percentage_reduction_target', Float),
    Column('Target_date', Integer),
    Column('Estimated_business_as_usual_absolute_emissions_in_target_year_metric_tonnes_CO2e', Float),
    Column('Intensity_unit_emissions_per', String),
    Column('Comment', String),
    Column('Population', Float),
    Column('Population_Year', Float),
    Column('City_Location', String),
    Column('Country_Location', String)
)

# Drop the table if it already exists to ensure we start fresh
inspector = inspect(engine)
if 'Cities_Emissions_Reduction_Targets_2017' in inspector.get_table_names():
    table.drop(engine)

# Create the table in the database
metadata.create_all(engine)

# Insert data into the table
df.to_sql('Cities_Emissions_Reduction_Targets_2017', engine, if_exists='append', index=False)

print("Data successfully inserted into the Cities_Emissions_Reduction_Targets_2017 table.")

Initial Data:
   Account No                   Organisation              City  \
0       54408                 Aarhus Kommune            Aarhus
1       63616  Abasan Al-Kabira Municipality  Abasan Al-Kabira
2       63616  Abasan Al-Kabira Municipality  Abasan Al-Kabira
3        1499        Ajuntament de Barcelona         Barcelona
4        1499        Ajuntament de Barcelona         Barcelona

              Country               Region  Access  C40  Reporting year  \
0             Denmark               Europe  Public  NaN            2017
1  State of Palestine  South and West Asia  Public  NaN            2017
2  State of Palestine  South and West Asia  Public  NaN            2017
3               Spain               Europe  Public  C40            2017
4               Spain               Europe  Public  C40            2017

    Type of target     Sector  ... Baseline emissions (metric tonnes CO2e)  \
0  Absolute target        NaN  ...                                     NaN
1  Absolute target  Buildings  ...                                 18320.0
2  Absolute target  Transport  ...                                  6893.0
3  Absolute target      Total  ...                                  4053.0
4  Absolute target  Buildings  ...                                  2164.0

   Percentage reduction target  Target date  \
0                        100.0         2030
1                         19.0         2020
2                          6.0         2020
3                         18.0         2020
4                          1.0         2020

  Estimated business as usual absolute emissions in target year (metric tonnes CO2e)  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   ​Intensity unit (emissions per)                                 Comment  \
0                              NaN                                     NaN
1                              NaN                                     NaN
2                              NaN                                     NaN
3                              NaN                                     NaN
4                              NaN  Residential, Commercial and Industrial

  Population  Population Year           City Location       Country Location
0   336000.0           2017.0  (56.168393, 10.137373)   (56.26392, 9.501785)
1    30000.0           2015.0  (31.323126, 34.344025)     (31.9522, 35.2332)
2    30000.0           2015.0  (31.323126, 34.344025)     (31.9522, 35.2332)
3  1608746.0           2016.0   (41.382271, 2.177506)  (40.463667, -3.74922)
4  1608746.0           2016.0   (41.382271, 2.177506)  (40.463667, -3.74922)

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 21 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   Account No                                                                          406 non-null    int64
 1   Organisation                                                                        406 non-null    object
 2   City                                                                                404 non-null    object
 3   Country                                                                             404 non-null    object
 4   Region                                                                              404 non-null    object
 5   Access                                                                              406 non-null    object
 6   C40                                                                                 94 non-null     object
 7   Reporting year                                                                      406 non-null    int64
 8   Type of target                                                                      406 non-null    object
 9   Sector                                                                              298 non-null    object
 10  Baseline year                                                                       372 non-null    object
 11  Baseline emissions (metric tonnes CO2e)                                             274 non-null    float64
 12  Percentage reduction target                                                         332 non-null    float64
 13  Target date                                                                         350 non-null    object
 14  Estimated business as usual absolute emissions in target year (metric tonnes CO2e)  31 non-null     float64
 15  ​Intensity unit (emissions per)                                                     23 non-null     object
 16  Comment                                                                             140 non-null    object
 17  Population                                                                          404 non-null    float64
 18  Population Year                                                                     404 non-null    float64
 19  City Location                                                                       404 non-null    object
 20  Country Location                                                                    404 non-null    object
dtypes: float64(5), int64(2), object(14)
memory usage: 66.7+ KB
None

Cleaned DataFrame:
   Account_No                   Organisation              City  \
0       54408                 Aarhus Kommune            Aarhus
1       63616  Abasan Al-Kabira Municipality  Abasan Al-Kabira
2       63616  Abasan Al-Kabira Municipality  Abasan Al-Kabira
3        1499        Ajuntament de Barcelona         Barcelona
4        1499        Ajuntament de Barcelona         Barcelona

              Country               Region  Access  C40  Reporting_year  \
0             Denmark               Europe  Public  NaN            2017
1  State of Palestine  South and West Asia  Public  NaN            2017
2  State of Palestine  South and West Asia  Public  NaN            2017
3               Spain               Europe  Public  C40            2017
4               Spain               Europe  Public  C40            2017

    Type_of_target     Sector  ...  Baseline_emissions_metric_tonnes_CO2e  \
0  Absolute target        NaN  ...                              1484767.0
1  Absolute target  Buildings  ...                                18320.0
2  Absolute target  Transport  ...                                 6893.0
3  Absolute target      Total  ...                                 4053.0
4  Absolute target  Buildings  ...                                 2164.0

   Percentage_reduction_target  Target_date  \
0                        100.0         2030
1                         19.0         2020
2                          6.0         2020
3                         18.0         2020
4                          1.0         2020

   Estimated_business_as_usual_absolute_emissions_in_target_year_metric_tonnes_CO2e  \
0                                          1348291.0
1                                          1348291.0
2                                          1348291.0
3                                          1348291.0
4                                          1348291.0

   Intensity_unit_emissions_per                                 Comment  \
0                           NaN                                     NaN
1                           NaN                                     NaN
2                           NaN                                     NaN
3                           NaN                                     NaN
4                           NaN  Residential, Commercial and Industrial

  Population  Population_Year           City_Location       Country_Location
0   336000.0           2017.0  (56.168393, 10.137373)   (56.26392, 9.501785)
1    30000.0           2015.0  (31.323126, 34.344025)     (31.9522, 35.2332)
2    30000.0           2015.0  (31.323126, 34.344025)     (31.9522, 35.2332)
3  1608746.0           2016.0   (41.382271, 2.177506)  (40.463667, -3.74922)
4  1608746.0           2016.0   (41.382271, 2.177506)  (40.463667, -3.74922)

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 403 entries, 0 to 405
Data columns (total 21 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   Account_No                                                                        403 non-null    int32
 1   Organisation                                                                      403 non-null    object
 2   City                                                                              403 non-null    object
 3   Country                                                                           403 non-null    object
 4   Region                                                                            403 non-null    object
 5   Access                                                                            403 non-null    object
 6   C40                                                                               94 non-null     object
 7   Reporting_year                                                                    403 non-null    int32
 8   Type_of_target                                                                    403 non-null    object
 9   Sector                                                                            298 non-null    object
 10  Baseline_year                                                                     403 non-null    int32
 11  Baseline_emissions_metric_tonnes_CO2e                                             403 non-null    float64
 12  Percentage_reduction_target                                                       403 non-null    float64
 13  Target_date                                                                       403 non-null    int32
 14  Estimated_business_as_usual_absolute_emissions_in_target_year_metric_tonnes_CO2e  403 non-null    float64
 15  Intensity_unit_emissions_per                                                      23 non-null     object
 16  Comment                                                                           140 non-null    object
 17  Population                                                                        403 non-null    float64
 18  Population_Year                                                                   403 non-null    float64
 19  City_Location                                                                     401 non-null    object
 20  Country_Location                                                                  401 non-null    object
dtypes: float64(5), int32(4), object(12)
memory usage: 63.0+ KB
None

Missing Values After Cleaning:
Account_No                                                                            0
Organisation                                                                          0
City                                                                                  0
Country                                                                               0
Region                                                                                0
Access                                                                                0
C40                                                                                 309
Reporting_year                                                                        0
Type_of_target                                                                        0
Sector                                                                              105
Baseline_year                                                                         0
Baseline_emissions_metric_tonnes_CO2e                                                 0
Percentage_reduction_target                                                           0
Target_date                                                                           0
Estimated_business_as_usual_absolute_emissions_in_target_year_metric_tonnes_CO2e      0
Intensity_unit_emissions_per                                                        380
Comment                                                                             263
Population                                                                            0
Population_Year                                                                       0
City_Location                                                                         2
Country_Location                                                                      2
dtype: int64
Data successfully inserted into the Cities_Emissions_Reduction_Targets_2017 table.

Explanation:
  Load CSV: Read the CSV file into a DataFrame using pd.read_csv   Display Initial Data: Print the first few rows and the structure of the DataFrame to understand its conten    Display Column Names: Print the column names to ensure correct column names are used in the subsequent ste
    Handle Missing Val      Fill numeric columns with median values to avoid skewing the        Fill categorical columns with a placeholder value to maintain consisy.
    Data Type Conversions: Convert date columns to a datetime format for consistency and easier manipuon.
    Standardize Formats: Standardize text formats (e.g., capitalizing city names) to maintain consncy.
    Remove Duplicates: Remove any duplicate rows to ensure each record iique.
    Trim and Clean Strings: Remove extra spaces from strialues.
    Consolidate Categories: Replace similar categories (e.g., 'Usa' to 'USA') for cstency.
    Validate Data: Ensure all percentage reduction targets are negative.
    Create Unique Identifiers: Create a unique identifier for each row based on the 'Accoun' column.
    Export Clean Data: Save the cleaned DataFrame to a CSV file.
    Define Connection Parameters: Set up the connection parame for MSSQL.
    Create and Insert Data: Write the cleaned data to a new table in the MSSQL database.

# 2023_Cities_Climate_Risk_and_Vulnerability_Assessments_20240207.csv

In [9]:
import pandas as pd
from sqlalchemy import create_engine

# Step 1: Load the CSV data into a DataFrame
file_path = '2023_Cities_Climate_Risk_and_Vulnerability_Assessments_20240207.csv'
df = pd.read_csv(file_path)

# Display the initial data structure
print("Initial Data:")
print(df.head())
print(df.info())

# Display the column names to identify the correct column names
print("\nColumn Names:")
print(df.columns)

# Step 2: Handling Missing Values
print("\nMissing Values Before Cleaning:")
print(df.isna().sum())

# Fill numeric columns with median values if they exist
numeric_columns = ['Population', 'Population Year', 'Year of publication or approval']
for column in numeric_columns:
    if column in df.columns:
        df[column] = df[column].fillna(df[column].median())

# Fill categorical columns with a placeholder value if they exist
categorical_columns = ['City', 'Country/Area', 'Organization Name', 'Assessment attachment and/or direct link']
for column in categorical_columns:
    if column in df.columns:
        df[column] = df[column].fillna(f'Unknown {column}')

# Convert 'Year of publication or approval' to datetime format and fill with a default value if they remain NaN
if 'Year of publication or approval' in df.columns:
    df['Year of publication or approval'] = pd.to_datetime(df['Year of publication or approval'], format='%Y', errors='coerce').dt.year
    df['Year of publication or approval'] = df['Year of publication or approval'].fillna(0)

# Step 3: Data Type Conversions
# Convert date columns to datetime format for consistency
if 'Year of publication or approval' in df.columns:
    df['Year of publication or approval'] = pd.to_datetime(df['Year of publication or approval'], format='%Y', errors='coerce').dt.year

# Step 4: Standardizing Formats
if 'City' in df.columns:
    df['City'] = df['City'].str.title()

# Step 5: Removing Duplicates
df.drop_duplicates(inplace=True)

# Step 6: Trimming and Cleaning Strings
if 'Organization Name' in df.columns:
    df['Organization Name'] = df['Organization Name'].str.strip()

# Step 7: Consolidating Categories
if 'Country/Area' in df.columns:
    df['Country/Area'] = df['Country/Area'].replace({'Usa': 'USA', 'Uk': 'United Kingdom'})

# Step 8: Validating Data
# Ensure all numeric columns have non-negative values
for column in numeric_columns:
    if column in df.columns:
        df = df[df[column] >= 0]

# Step 9: Creating Unique Identifiers
if 'Organization Number' in df.columns:
    df['id'] = pd.factorize(df['Organization Number'])[0] + 1

# Step 10: Exporting Clean Data
cleaned_file_path = 'cleaned_data_MSSQL_2023_Cities_Climate_Risk_and_Vulnerability_Assessments.csv'
df.to_csv(cleaned_file_path, index=False)

# Display the cleaned data structure and info
print("\nCleaned Data:")
print(df.head())
print(df.info())

print("\nMissing Values After Cleaning:")
print(df.isna().sum())

# Step 11: Define the connection parameters
server = 'JEFFREY'
database = 'EksamensProjekt_DB'
username = 'Oechsner'
password = '1234'

# Create the connection string
connection_string = f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'

# Create the engine
engine = create_engine(connection_string)

# Step 12: Create a new table and insert data
table_name = 'Cities_Climate_Risk_and_Vulnerability_Assessments'

# Write the data to the SQL table
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data successfully inserted into the {table_name} table.")

Initial Data:
  Questionnaire  Organization Number                Organization Name  \
0   Cities 2023               840926      Prefeitura de Serra Talhada
1   Cities 2023                51075                 City of Shenzhen
2   Cities 2023               863190                            Renca
3   Cities 2023               930366  Municipalidad Distrital de Yura
4   Cities 2023                60236          Trelleborg Municipality

         City Country/Area     CDP Region  C40 City  GCoM City  Access  \
0         NaN       Brazil  Latin America     False       True  public
1    Shenzhen        China      East Asia      True      False  public
2         NaN        Chile  Latin America     False      False  public
3         NaN         Peru  Latin America     False       True  public
4  Trelleborg       Sweden         Europe     False       True  public

            Assessment attachment and/or direct link  \
0  https://drive.google.com/file/d/19DMxxK532IQSL...
1                                                NaN
2                          PLCC_Renca (08 Abril).pdf
3  https://sigrid.cenepred.gob.pe/sigridv3/docume...
4  https://moten.trelleborg.se/welcome-sv/namnder...

                    Confirm attachment/link provided  \
0  The assessment can be accessed (unrestricted) ...
1  The assessment can be accessed (unrestricted) ...
2                   The assessment has been attached
3  The assessment can be accessed (unrestricted) ...
4  The assessment can be accessed (unrestricted) ...

  Boundary of assessment relative to jurisdiction boundary  \
0  Same - covers entire jurisdiction and nothing ...
1  Same - covers entire jurisdiction and nothing ...
2  Same - covers entire jurisdiction and nothing ...
3  Same - covers entire jurisdiction and nothing ...
4  Same - covers entire jurisdiction and nothing ...

   Year of publication or approval  \
0                           2022.0
1                           2022.0
2                           2019.0
3                           2022.0
4                           2018.0

                    Factors considered in assessment  \
0  Assessment considers vulnerable populations; A...
1  Assessment considers nature; Assessment consid...
2  A process has been established for prioritizin...
3  Identified hazards have been incorporated into...
4  A process has been established for prioritizin...

                     Primary author(s) of assessment  \
0  Dedicated team within jurisdiction; Relevant d...
1  Consultant; Dedicated team within jurisdiction...
2                            Question not applicable
3                 Dedicated team within jurisdiction
4                 Dedicated team within jurisdiction

  Does the city have adaptation goal(s) and/or an adaptation plan?  \
0             Adaptation goal(s) and adaptation plan
1                                    Adaptation plan
2             Adaptation goal(s) and adaptation plan
3                                  Incomplete report
4             Adaptation goal(s) and adaptation plan

   Population  Population Year            City Location  \
0       92228           2023.0                      NaN
1    17662000           2022.0  POINT (113.813 22.9175)
2      162517           2022.0                      NaN
3       33346           2017.0                      NaN
4       46649           2022.0  POINT (13.1569 55.3751)

              Last update
0  02/07/2024 04:14:16 AM
1  02/07/2024 04:14:16 AM
2  02/07/2024 04:14:16 AM
3  02/07/2024 04:14:16 AM
4  02/07/2024 04:14:16 AM
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370 entries, 0 to 1369
Data columns (total 20 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Questionnaire                                                     1370 non-null   object
 1   Organization Number                                               1370 non-null   int64
 2   Organization Name                                                 1370 non-null   object
 3   City                                                              931 non-null    object
 4   Country/Area                                                      1370 non-null   object
 5   CDP Region                                                        1370 non-null   object
 6   C40 City                                                          1370 non-null   bool
 7   GCoM City                                                         1370 non-null   bool
 8   Access                                                            1370 non-null   object
 9   Assessment attachment and/or direct link                          1333 non-null   object
 10  Confirm attachment/link provided                                  1370 non-null   object
 11  Boundary of assessment relative to jurisdiction boundary          1358 non-null   object
 12  Year of publication or approval                                   1344 non-null   float64
 13  Factors considered in assessment                                  1319 non-null   object
 14  Primary author(s) of assessment                                   1320 non-null   object
 15  Does the city have adaptation goal(s) and/or an adaptation plan?  1370 non-null   object
 16  Population                                                        1370 non-null   int64
 17  Population Year                                                   1362 non-null   float64
 18  City Location                                                     800 non-null    object
 19  Last update                                                       1370 non-null   object
dtypes: bool(2), float64(2), int64(2), object(14)
memory usage: 195.5+ KB
None

Column Names:
Index(['Questionnaire', 'Organization Number', 'Organization Name', 'City',
       'Country/Area', 'CDP Region', 'C40 City', 'GCoM City', 'Access',
       'Assessment attachment and/or direct link',
       'Confirm attachment/link provided',
       'Boundary of assessment relative to jurisdiction boundary',
       'Year of publication or approval', 'Factors considered in assessment',
       'Primary author(s) of assessment',
       'Does the city have adaptation goal(s) and/or an adaptation plan?',
       'Population', 'Population Year', 'City Location', 'Last update'],
      dtype='object')

Missing Values Before Cleaning:
Questionnaire                                                         0
Organization Number                                                   0
Organization Name                                                     0
City                                                                439
Country/Area                                                          0
CDP Region                                                            0
C40 City                                                              0
GCoM City                                                             0
Access                                                                0
Assessment attachment and/or direct link                             37
Confirm attachment/link provided                                      0
Boundary of assessment relative to jurisdiction boundary             12
Year of publication or approval                                      26
Factors considered in assessment                                     51
Primary author(s) of assessment                                      50
Does the city have adaptation goal(s) and/or an adaptation plan?      0
Population                                                            0
Population Year                                                       8
City Location                                                       570
Last update                                                           0
dtype: int64

Cleaned Data:
  Questionnaire  Organization Number                Organization Name  \
0   Cities 2023               840926      Prefeitura de Serra Talhada
1   Cities 2023                51075                 City of Shenzhen
2   Cities 2023               863190                            Renca
3   Cities 2023               930366  Municipalidad Distrital de Yura
4   Cities 2023                60236          Trelleborg Municipality

           City Country/Area     CDP Region  C40 City  GCoM City  Access  \
0  Unknown City       Brazil  Latin America     False       True  public
1      Shenzhen        China      East Asia      True      False  public
2  Unknown City        Chile  Latin America     False      False  public
3  Unknown City         Peru  Latin America     False       True  public
4    Trelleborg       Sweden         Europe     False       True  public

            Assessment attachment and/or direct link  ...  \
0  https://drive.google.com/file/d/19DMxxK532IQSL...  ...
1   Unknown Assessment attachment and/or direct link  ...
2                          PLCC_Renca (08 Abril).pdf  ...
3  https://sigrid.cenepred.gob.pe/sigridv3/docume...  ...
4  https://moten.trelleborg.se/welcome-sv/namnder...  ...

  Boundary of assessment relative to jurisdiction boundary  \
0  Same - covers entire jurisdiction and nothing ...
1  Same - covers entire jurisdiction and nothing ...
2  Same - covers entire jurisdiction and nothing ...
3  Same - covers entire jurisdiction and nothing ...
4  Same - covers entire jurisdiction and nothing ...

  Year of publication or approval  \
0                            2022
1                            2022
2                            2019
3                            2022
4                            2018

                    Factors considered in assessment  \
0  Assessment considers vulnerable populations; A...
1  Assessment considers nature; Assessment consid...
2  A process has been established for prioritizin...
3  Identified hazards have been incorporated into...
4  A process has been established for prioritizin...

                     Primary author(s) of assessment  \
0  Dedicated team within jurisdiction; Relevant d...
1  Consultant; Dedicated team within jurisdiction...
2                            Question not applicable
3                 Dedicated team within jurisdiction
4                 Dedicated team within jurisdiction

  Does the city have adaptation goal(s) and/or an adaptation plan? Population  \
0             Adaptation goal(s) and adaptation plan                    92228
1                                    Adaptation plan                 17662000
2             Adaptation goal(s) and adaptation plan                   162517
3                                  Incomplete report                    33346
4             Adaptation goal(s) and adaptation plan                    46649

   Population Year            City Location             Last update id
0           2023.0                      NaN  02/07/2024 04:14:16 AM  1
1           2022.0  POINT (113.813 22.9175)  02/07/2024 04:14:16 AM  2
2           2022.0                      NaN  02/07/2024 04:14:16 AM  3
3           2017.0                      NaN  02/07/2024 04:14:16 AM  4
4           2022.0  POINT (13.1569 55.3751)  02/07/2024 04:14:16 AM  5

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370 entries, 0 to 1369
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Questionnaire                                                     1370 non-null   object
 1   Organization Number                                               1370 non-null   int64
 2   Organization Name                                                 1370 non-null   object
 3   City                                                              1370 non-null   object
 4   Country/Area                                                      1370 non-null   object
 5   CDP Region                                                        1370 non-null   object
 6   C40 City                                                          1370 non-null   bool
 7   GCoM City                                                         1370 non-null   bool
 8   Access                                                            1370 non-null   object
 9   Assessment attachment and/or direct link                          1370 non-null   object
 10  Confirm attachment/link provided                                  1370 non-null   object
 11  Boundary of assessment relative to jurisdiction boundary          1358 non-null   object
 12  Year of publication or approval                                   1370 non-null   int32
 13  Factors considered in assessment                                  1319 non-null   object
 14  Primary author(s) of assessment                                   1320 non-null   object
 15  Does the city have adaptation goal(s) and/or an adaptation plan?  1370 non-null   object
 16  Population                                                        1370 non-null   int64
 17  Population Year                                                   1370 non-null   float64
 18  City Location                                                     800 non-null    object
 19  Last update                                                       1370 non-null   object
 20  id                                                                1370 non-null   int64
dtypes: bool(2), float64(1), int32(1), int64(3), object(14)
memory usage: 200.8+ KB
None

Missing Values After Cleaning:
Questionnaire                                                         0
Organization Number                                                   0
Organization Name                                                     0
City                                                                  0
Country/Area                                                          0
CDP Region                                                            0
C40 City                                                              0
GCoM City                                                             0
Access                                                                0
Assessment attachment and/or direct link                              0
Confirm attachment/link provided                                      0
Boundary of assessment relative to jurisdiction boundary             12
Year of publication or approval                                       0
Factors considered in assessment                                     51
Primary author(s) of assessment                                      50
Does the city have adaptation goal(s) and/or an adaptation plan?      0
Population                                                            0
Population Year                                                       0
City Location                                                       570
Last update                                                           0
id                                                                    0
dtype: int64
Data successfully inserted into the Cities_Climate_Risk_and_Vulnerability_Assessments table.

In [65]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float
from sqlalchemy import inspect

# Step 1: Load the CSV data into a DataFrame
file_path = '2023_Cities_Climate_Risk_and_Vulnerability_Assessments_20240207.csv'
df = pd.read_csv(file_path)

# Display the initial data structure
print("Initial Data:")
print(df.head(10))  # Display more rows for better inspection
print(df.info())

# Step 2: Clean column names: remove leading/trailing spaces, hidden characters, and replace spaces with underscores
df.columns = df.columns.str.strip().str.replace('\u200b', '').str.replace(' ', '_')

# Display the cleaned column names
print("\nCleaned Column Names:")
print(df.columns)

# Step 3: Handle missing values
# Fill numeric columns with median values
numeric_columns = [
    'Year_of_publication_or_approval', 
    'Population', 
    'Population_Year'
]

for column in numeric_columns:
    if column in df.columns:
        df[column] = df[column].fillna(df[column].median())

# Fill categorical columns with a placeholder value
categorical_columns = [
    'City', 'Country/Area', 'CDP_Region', 'Organization_Name', 'Access',
    'Assessment_attachment_and/or_direct_link', 'Confirm_attachment/link_provided',
    'Boundary_of_assessment_relative_to_jurisdiction_boundary', 'Factors_considered_in_assessment',
    'Primary_author(s)_of_assessment', 'Does_the_city_have_adaptation_goal(s)_and/or_an_adaptation_plan?',
    'City_Location'
]

for column in categorical_columns:
    if column in df.columns:
        df[column] = df[column].fillna(f'Unknown_{column}')

# Convert date columns to integer format and fill with a default value if they remain NaN
date_columns = ['Year_of_publication_or_approval']

for column in date_columns:
    if column in df.columns:
        df[column] = pd.to_datetime(df[column], format='%Y', errors='coerce').dt.year
        df[column] = df[column].fillna(0).astype(int)

# Ensure that columns expected to be integers do not contain non-integer values
integer_columns = ['Organization_Number', 'Year_of_publication_or_approval', 'Population', 'Population_Year']

for column in integer_columns:
    if column in df.columns:
        df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0).astype(int)

# Step 4: Standardize formats and handle duplicates
if 'City' in df.columns:
    df['City'] = df['City'].str.title()

df.drop_duplicates(inplace=True)

if 'Country/Area' in df.columns:
    df['Country/Area'] = df['Country/Area'].replace({'Usa': 'USA', 'Uk': 'United_Kingdom'})

# Step 5: Ensure column names match the SQL Server schema
df.rename(columns={
    'Organization_Number': 'Account_No',
    'Country/Area': 'Country',
    'Year_of_publication_or_approval': 'Reporting_year',
    'Organization_Name': 'Organization_Name',
    'Access': 'Access',
    'CDP_Region': 'Region'
}, inplace=True)

# Ensure the DataFrame has the expected columns
expected_columns = [
    'Account_No', 'City', 'Country', 'Region', 'Reporting_year',
    'Organization_Name', 'Access', 'Population', 'Population_Year',
    'Assessment_attachment_and/or_direct_link', 'Confirm_attachment/link_provided',
    'Boundary_of_assessment_relative_to_jurisdiction_boundary', 'Factors_considered_in_assessment',
    'Primary_author(s)_of_assessment', 'Does_the_city_have_adaptation_goal(s)_and/or_an_adaptation_plan?',
    'City_Location', 'Last_update'
]

# Add missing columns if they don't exist
for column in expected_columns:
    if column not in df.columns:
        df[column] = None

# Reorder the columns to match the expected schema
df = df[expected_columns]

# Verify the cleaned DataFrame before inserting
print("\nCleaned DataFrame:")
print(df.head(10))  # Display more rows for better inspection
print(df.info())

print("\nMissing Values After Cleaning:")
print(df.isna().sum())

# Exporting Clean Data
cleaned_file_path = 'cleaned_data_MSSQL_2023_Cities_Climate_Risk_and_Vulnerability_Assessments.csv'
df.to_csv(cleaned_file_path, index=False)

# Step 6: Insert the cleaned DataFrame into MSSQL

# Define the connection parameters
server = 'JEFFREY'
database = 'EksamensProjekt_DB'
username = 'Oechsner'
password = '1234'
connection_string = f'mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server'
engine = create_engine(connection_string)

# Define the metadata and table schema
metadata = MetaData()

# Define the table schema with 'id' as primary key
table = Table(
    'Cities_Climate_Risk_and_Vulnerability_Assessments_2023', metadata,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('Account_No', Integer),
    Column('City', String),
    Column('Country', String),
    Column('Region', String),
    Column('Reporting_year', Integer),
    Column('Organization_Name', String),
    Column('Access', String),
    Column('Population', Integer),
    Column('Population_Year', Integer),
    Column('Assessment_attachment_and/or_direct_link', String),
    Column('Confirm_attachment/link_provided', String),
    Column('Boundary_of_assessment_relative_to_jurisdiction_boundary', String),
    Column('Factors_considered_in_assessment', String),
    Column('Primary_author(s)_of_assessment', String),
    Column('Does_the_city_have_adaptation_goal(s)_and/or_an_adaptation_plan?', String),
    Column('City_Location', String),
    Column('Last_update', String)
)

# Drop the table if it already exists to ensure we start fresh
inspector = inspect(engine)
if 'Cities_Climate_Risk_and_Vulnerability_Assessments_2023' in inspector.get_table_names():
    table.drop(engine)

# Create the table in the database
metadata.create_all(engine)

# Insert data into the table
df.to_sql('Cities_Climate_Risk_and_Vulnerability_Assessments_2023', engine, if_exists='append', index=False)

print("Data successfully inserted into the Cities_Climate_Risk_and_Vulnerability_Assessments_2023 table.")

Initial Data:
  Questionnaire  Organization Number                Organization Name  \
0   Cities 2023               840926      Prefeitura de Serra Talhada
1   Cities 2023                51075                 City of Shenzhen
2   Cities 2023               863190                            Renca
3   Cities 2023               930366  Municipalidad Distrital de Yura
4   Cities 2023                60236          Trelleborg Municipality
5   Cities 2023               863463                Valle de Santiago
6   Cities 2023                54125                City of Boise, ID
7   Cities 2023                35857           City of Cincinnati, OH
8   Cities 2023               850566          Prefeitura de Piraquara
9   Cities 2023                54365          Kota Kinabalu City Hall

         City              Country/Area                CDP Region  C40 City  \
0         NaN                    Brazil             Latin America     False
1    Shenzhen                     China                 East Asia      True
2         NaN                     Chile             Latin America     False
3         NaN                      Peru             Latin America     False
4  Trelleborg                    Sweden                    Europe     False
5         NaN                    Mexico             Latin America     False
6       Boise  United States of America  United States of America     False
7  Cincinnati  United States of America  United States of America     False
8   Piraquara                    Brazil             Latin America     False
9         NaN                  Malaysia            Southeast Asia     False

   GCoM City  Access           Assessment attachment and/or direct link  \
0       True  public  https://drive.google.com/file/d/19DMxxK532IQSL...
1      False  public                                                NaN
2      False  public                          PLCC_Renca (08 Abril).pdf
3       True  public  https://sigrid.cenepred.gob.pe/sigridv3/docume...
4       True  public  https://moten.trelleborg.se/welcome-sv/namnder...
5       True  public           15 PMDUOET versión INTEGRAL Cap.4-10.pdf
6      False  public  https://www.cityofboise.org/departments/public...
7       True  public  https://www.hamiltoncountyohio.gov/emergency_m...
8      False  public    http://sisvuclima.mma.gov.br/visualizar_indice/
9       True  public                                  Land use planning

                    Confirm attachment/link provided  \
0  The assessment can be accessed (unrestricted) ...
1  The assessment can be accessed (unrestricted) ...
2                   The assessment has been attached
3  The assessment can be accessed (unrestricted) ...
4  The assessment can be accessed (unrestricted) ...
5                   The assessment has been attached
6  The assessment can be accessed (unrestricted) ...
7  The assessment can be accessed (unrestricted) ...
8  The assessment can be accessed (unrestricted) ...
9  The assessment can be accessed (unrestricted) ...

  Boundary of assessment relative to jurisdiction boundary  \
0  Same - covers entire jurisdiction and nothing ...
1  Same - covers entire jurisdiction and nothing ...
2  Same - covers entire jurisdiction and nothing ...
3  Same - covers entire jurisdiction and nothing ...
4  Same - covers entire jurisdiction and nothing ...
5  Same - covers entire jurisdiction and nothing ...
6  Same - covers entire jurisdiction and nothing ...
7  Larger - covers the whole jurisdiction and adj...
8  Same - covers entire jurisdiction and nothing ...
9  Same - covers entire jurisdiction and nothing ...

   Year of publication or approval  \
0                           2022.0
1                           2022.0
2                           2019.0
3                           2022.0
4                           2018.0
5                           2021.0
6                           2016.0
7                           2018.0
8                           2017.0
9                           2019.0

                    Factors considered in assessment  \
0  Assessment considers vulnerable populations; A...
1  Assessment considers nature; Assessment consid...
2  A process has been established for prioritizin...
3  Identified hazards have been incorporated into...
4  A process has been established for prioritizin...
5  Assessment considers nature; Assessment consid...
6                Assessment considers water security
7  Assessment considers nature; Assessment consid...
8  Assessment considers nature; Identified hazard...
9                                                NaN

                     Primary author(s) of assessment  \
0  Dedicated team within jurisdiction; Relevant d...
1  Consultant; Dedicated team within jurisdiction...
2                            Question not applicable
3                 Dedicated team within jurisdiction
4                 Dedicated team within jurisdiction
5  Consultant; Dedicated team within jurisdiction...
6         Other, please specify: University of Idaho
7             Regional/ state/ provincial government
8                       National/ central government
9                                                NaN

  Does the city have adaptation goal(s) and/or an adaptation plan?  \
0             Adaptation goal(s) and adaptation plan
1                                    Adaptation plan
2             Adaptation goal(s) and adaptation plan
3                                  Incomplete report
4             Adaptation goal(s) and adaptation plan
5             Adaptation goal(s) and adaptation plan
6             Adaptation goal(s) and adaptation plan
7             Adaptation goal(s) and adaptation plan
8                                 Adaptation goal(s)
9                                  Incomplete report

   Population  Population Year            City Location  \
0       92228           2023.0                      NaN
1    17662000           2022.0  POINT (113.813 22.9175)
2      162517           2022.0                      NaN
3       33346           2017.0                      NaN
4       46649           2022.0  POINT (13.1569 55.3751)
5      150054           2020.0                      NaN
6      236634           2022.0                      NaN
7      308935           2021.0  POINT (-84.512 39.1031)
8      118730           2022.0                      NaN
9      500425           2020.0                      NaN

              Last update
0  02/07/2024 04:14:16 AM
1  02/07/2024 04:14:16 AM
2  02/07/2024 04:14:16 AM
3  02/07/2024 04:14:16 AM
4  02/07/2024 04:14:16 AM
5  02/07/2024 04:14:16 AM
6  02/07/2024 04:14:16 AM
7  02/07/2024 04:14:16 AM
8  02/07/2024 04:14:16 AM
9  02/07/2024 04:14:16 AM
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370 entries, 0 to 1369
Data columns (total 20 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Questionnaire                                                     1370 non-null   object
 1   Organization Number                                               1370 non-null   int64
 2   Organization Name                                                 1370 non-null   object
 3   City                                                              931 non-null    object
 4   Country/Area                                                      1370 non-null   object
 5   CDP Region                                                        1370 non-null   object
 6   C40 City                                                          1370 non-null   bool
 7   GCoM City                                                         1370 non-null   bool
 8   Access                                                            1370 non-null   object
 9   Assessment attachment and/or direct link                          1333 non-null   object
 10  Confirm attachment/link provided                                  1370 non-null   object
 11  Boundary of assessment relative to jurisdiction boundary          1358 non-null   object
 12  Year of publication or approval                                   1344 non-null   float64
 13  Factors considered in assessment                                  1319 non-null   object
 14  Primary author(s) of assessment                                   1320 non-null   object
 15  Does the city have adaptation goal(s) and/or an adaptation plan?  1370 non-null   object
 16  Population                                                        1370 non-null   int64
 17  Population Year                                                   1362 non-null   float64
 18  City Location                                                     800 non-null    object
 19  Last update                                                       1370 non-null   object
dtypes: bool(2), float64(2), int64(2), object(14)
memory usage: 195.5+ KB
None

Cleaned Column Names:
Index(['Questionnaire', 'Organization_Number', 'Organization_Name', 'City',
       'Country/Area', 'CDP_Region', 'C40_City', 'GCoM_City', 'Access',
       'Assessment_attachment_and/or_direct_link',
       'Confirm_attachment/link_provided',
       'Boundary_of_assessment_relative_to_jurisdiction_boundary',
       'Year_of_publication_or_approval', 'Factors_considered_in_assessment',
       'Primary_author(s)_of_assessment',
       'Does_the_city_have_adaptation_goal(s)_and/or_an_adaptation_plan?',
       'Population', 'Population_Year', 'City_Location', 'Last_update'],
      dtype='object')

Cleaned DataFrame:
   Account_No          City                   Country  \
0      840926  Unknown_City                    Brazil
1       51075      Shenzhen                     China
2      863190  Unknown_City                     Chile
3      930366  Unknown_City                      Peru
4       60236    Trelleborg                    Sweden
5      863463  Unknown_City                    Mexico
6       54125         Boise  United States of America
7       35857    Cincinnati  United States of America
8      850566     Piraquara                    Brazil
9       54365  Unknown_City                  Malaysia

                     Region  Reporting_year                Organization_Name  \
0             Latin America            2022      Prefeitura de Serra Talhada
1                 East Asia            2022                 City of Shenzhen
2             Latin America            2019                            Renca
3             Latin America            2022  Municipalidad Distrital de Yura
4                    Europe            2018          Trelleborg Municipality
5             Latin America            2021                Valle de Santiago
6  United States of America            2016                City of Boise, ID
7  United States of America            2018           City of Cincinnati, OH
8             Latin America            2017          Prefeitura de Piraquara
9            Southeast Asia            2019          Kota Kinabalu City Hall

   Access  Population  Population_Year  \
0  public       92228             2023
1  public    17662000             2022
2  public      162517             2022
3  public       33346             2017
4  public       46649             2022
5  public      150054             2020
6  public      236634             2022
7  public      308935             2021
8  public      118730             2022
9  public      500425             2020

            Assessment_attachment_and/or_direct_link  \
0  https://drive.google.com/file/d/19DMxxK532IQSL...
1   Unknown_Assessment_attachment_and/or_direct_link
2                          PLCC_Renca (08 Abril).pdf
3  https://sigrid.cenepred.gob.pe/sigridv3/docume...
4  https://moten.trelleborg.se/welcome-sv/namnder...
5           15 PMDUOET versión INTEGRAL Cap.4-10.pdf
6  https://www.cityofboise.org/departments/public...
7  https://www.hamiltoncountyohio.gov/emergency_m...
8    http://sisvuclima.mma.gov.br/visualizar_indice/
9                                  Land use planning

                    Confirm_attachment/link_provided  \
0  The assessment can be accessed (unrestricted) ...
1  The assessment can be accessed (unrestricted) ...
2                   The assessment has been attached
3  The assessment can be accessed (unrestricted) ...
4  The assessment can be accessed (unrestricted) ...
5                   The assessment has been attached
6  The assessment can be accessed (unrestricted) ...
7  The assessment can be accessed (unrestricted) ...
8  The assessment can be accessed (unrestricted) ...
9  The assessment can be accessed (unrestricted) ...

  Boundary_of_assessment_relative_to_jurisdiction_boundary  \
0  Same - covers entire jurisdiction and nothing ...
1  Same - covers entire jurisdiction and nothing ...
2  Same - covers entire jurisdiction and nothing ...
3  Same - covers entire jurisdiction and nothing ...
4  Same - covers entire jurisdiction and nothing ...
5  Same - covers entire jurisdiction and nothing ...
6  Same - covers entire jurisdiction and nothing ...
7  Larger - covers the whole jurisdiction and adj...
8  Same - covers entire jurisdiction and nothing ...
9  Same - covers entire jurisdiction and nothing ...

                    Factors_considered_in_assessment  \
0  Assessment considers vulnerable populations; A...
1  Assessment considers nature; Assessment consid...
2  A process has been established for prioritizin...
3  Identified hazards have been incorporated into...
4  A process has been established for prioritizin...
5  Assessment considers nature; Assessment consid...
6                Assessment considers water security
7  Assessment considers nature; Assessment consid...
8  Assessment considers nature; Identified hazard...
9           Unknown_Factors_considered_in_assessment

                     Primary_author(s)_of_assessment  \
0  Dedicated team within jurisdiction; Relevant d...
1  Consultant; Dedicated team within jurisdiction...
2                            Question not applicable
3                 Dedicated team within jurisdiction
4                 Dedicated team within jurisdiction
5  Consultant; Dedicated team within jurisdiction...
6         Other, please specify: University of Idaho
7             Regional/ state/ provincial government
8                       National/ central government
9            Unknown_Primary_author(s)_of_assessment

  Does_the_city_have_adaptation_goal(s)_and/or_an_adaptation_plan?  \
0             Adaptation goal(s) and adaptation plan
1                                    Adaptation plan
2             Adaptation goal(s) and adaptation plan
3                                  Incomplete report
4             Adaptation goal(s) and adaptation plan
5             Adaptation goal(s) and adaptation plan
6             Adaptation goal(s) and adaptation plan
7             Adaptation goal(s) and adaptation plan
8                                 Adaptation goal(s)
9                                  Incomplete report

             City_Location             Last_update
0    Unknown_City_Location  02/07/2024 04:14:16 AM
1  POINT (113.813 22.9175)  02/07/2024 04:14:16 AM
2    Unknown_City_Location  02/07/2024 04:14:16 AM
3    Unknown_City_Location  02/07/2024 04:14:16 AM
4  POINT (13.1569 55.3751)  02/07/2024 04:14:16 AM
5    Unknown_City_Location  02/07/2024 04:14:16 AM
6    Unknown_City_Location  02/07/2024 04:14:16 AM
7  POINT (-84.512 39.1031)  02/07/2024 04:14:16 AM
8    Unknown_City_Location  02/07/2024 04:14:16 AM
9    Unknown_City_Location  02/07/2024 04:14:16 AM
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370 entries, 0 to 1369
Data columns (total 17 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Account_No                                                        1370 non-null   int32
 1   City                                                              1370 non-null   object
 2   Country                                                           1370 non-null   object
 3   Region                                                            1370 non-null   object
 4   Reporting_year                                                    1370 non-null   int32
 5   Organization_Name                                                 1370 non-null   object
 6   Access                                                            1370 non-null   object
 7   Population                                                        1370 non-null   int32
 8   Population_Year                                                   1370 non-null   int32
 9   Assessment_attachment_and/or_direct_link                          1370 non-null   object
 10  Confirm_attachment/link_provided                                  1370 non-null   object
 11  Boundary_of_assessment_relative_to_jurisdiction_boundary          1370 non-null   object
 12  Factors_considered_in_assessment                                  1370 non-null   object
 13  Primary_author(s)_of_assessment                                   1370 non-null   object
 14  Does_the_city_have_adaptation_goal(s)_and/or_an_adaptation_plan?  1370 non-null   object
 15  City_Location                                                     1370 non-null   object
 16  Last_update                                                       1370 non-null   object
dtypes: int32(4), object(13)
memory usage: 160.7+ KB
None

Missing Values After Cleaning:
Account_No                                                          0
City                                                                0
Country                                                             0
Region                                                              0
Reporting_year                                                      0
Organization_Name                                                   0
Access                                                              0
Population                                                          0
Population_Year                                                     0
Assessment_attachment_and/or_direct_link                            0
Confirm_attachment/link_provided                                    0
Boundary_of_assessment_relative_to_jurisdiction_boundary            0
Factors_considered_in_assessment                                    0
Primary_author(s)_of_assessment                                     0
Does_the_city_have_adaptation_goal(s)_and/or_an_adaptation_plan?    0
City_Location                                                       0
Last_update                                                         0
dtype: int64
Data successfully inserted into the Cities_Climate_Risk_and_Vulnerability_Assessments_2023 table.

Explanation:
  Load CSV: Read the CSV file into a DataFrame using pd.read_csv   Display Initial Data: Print the first few rows and the structure of the DataFrame to understand its conten    Display Column Names: Print the column names to ensure correct column names are used in the subsequent ste
    Handle Missing Val      Fill numeric columns with median values to avoid skewing the        Fill categorical columns with a placeholder value to maintain consisy.
    Data Type Conversions: Convert date columns to a datetime format for consistency and easier manipuon.
    Standardize Formats: Standardize text formats (e.g., capitalizing city names) to maintain consncy.
    Remove Duplicates: Remove any duplicate rows to ensure each record iique.
    Trim and Clean Strings: Remove extra spaces from strialues.
    Consolidate Categories: Replace similar categories (e.g., 'Usa' to 'USA') for cstency.
    Validate Data: Ensure all numeric columns have non-nega values.
    Create Unique Identifiers: Create a unique identifier for each row based on the 'Organization Nu' column.
    Export Clean Data: Save the cleaned DataFrame to aw CSV file.
    Define Connection Parameters: Set up the connection parame for MSSQL.
    Create and Insert Data: Write the cleaned data to a new table in the MSSQL database.